### ISSUE TITLE
NoBackendError('No backend available')

### ISSUE THREAD

**Issue by DB-1** [andrewdodd/ccsniffpiper#10]
Hi, i'm running ccsniffpiper on MacOS Catalina and recently came across this error when trying to run the programme.  Could you possibly let me know what this could be and a fix.  Many thanks

FIFO /tmp/ccsniffpiper exists. Using it
Commands:
c: Print current RF Channel
n: Trigger new pcap header before the next frame
h,?: Print this message
[11,26]: Change RF channel
s: Start/stop the packet capture
q: Quit
Traceback (most recent call last):
  File "ccsniffpiper.py", line 568, in <module>
    snifferDev = CC2531(handlerDispatcher, args.channel)
  File "ccsniffpiper.py", line 309, in __init__
    self.dev = usb.core.find(idVendor=0x0451, idProduct=0x16ae)
  File "/Users/DavesMac/Library/Python/2.7/lib/python/site-packages/usb/core.py", line 1263, in find
    raise NoBackendError('No backend available')
usb.core.NoBackendError: No backend available

**Comment by andrewdodd** [comment]
Hi Dave,

Unfortunately I haven't used this library in a long time (I no longer work with 802.15.4 devices unfortunately!).

It looks to me that it is related to not having the correct dependencies installed. From memory (and the brief mention in the readme), you have to install pyusb with a version from at least 1.0 onwards.

E.g. if you run: 

    > pip freeze

It should print out the libraries you have installed.

Running:

    > pip install pyusb

should install "a" version....you might have to do something like:

    > pip install pyusb>=1.0

or 

    > pip install pyusb==1.0

instead?

**Comment by DB-1** [comment]
Hi Thanks for that, i've made progress.

I now have this error

ccsniffpiper.py:177: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
  logger.warn('FIFO %s exists. Using it' % (self.out_fifo,))
FIFO /tmp/ccsniffpiper exists. Using it
Commands:
c: Print current RF Channel
n: Trigger new pcap header before the next frame
h,?: Print this message
[11,26]: Change RF channel
s: Start/stop the packet capture
q: Quit
Traceback (most recent call last):
  File "ccsniffpiper.py", line 573, in <module>
    snifferDev = CC2531(handlerDispatcher, args.channel)
  File "ccsniffpiper.py", line 318, in __init__
    raise IOError("Device not found")
OSError: Device not found

I'm assuming its because my MacOS Catalina cannot find the cc2531?  Is there anything I need to do other than plug it in?   Apologies for the questions, this is my first attempt at all this for my final uni dissertion and i appreciate you're not here to hold my hand.

Many thanks

**Comment by andrewdodd** [comment]
@DB-1 , any luck?
