### ISSUE TITLE
Unable to run on Mac

### ISSUE THREAD

**Issue by IgorGanapolsky** [andrewdodd/ccsniffpiper#11]
❯ python ccsniffpiper.py
>Traceback (most recent call last):
  File "ccsniffpiper.py", line 55, in <module>
    import usb.core
ImportError: No module named usb.core

**Comment by andrewdodd** [comment]
Hey Igor,

Unfortunately I don't have one of these dongles anymore, so I can't help too much. However, I think this is due to you needing to install PyUSB.

E.g. I think this should help:

    pip install pyusb

**Comment by IgorGanapolsky** [comment]
Yes, that command works now.  Thanks.
